version: "3.9"
services:
  mcp-google:
    build: .
    container_name: mcp-google
    env_file:
      - .env
    ports:
      - "3333:3333"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/dist/server.js", "--healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
